package:
  name: molpx
  # version number: [base tag]+[commits-upstream]_[git_hash]
  # eg. v2.0+0_g8824162
  version: {{ GIT_DESCRIBE_TAG[1:] + '+' +GIT_BUILD_STR}}
source:
  path: ../..

build:
  number: 0 # remember to change this manually every build until automated
  noarch: python
  script: python -m pip install --no-deps --ignore-installed -v .

requirements:
  build:
    - python
    - pip
  run:
    - ipympl
    - nglview >=1
    - notebook
    - pyemma
    - python
    - scikit-learn

test:
  requires:
    - pytest-cov
    - nbval
    - nose >= 1
  imports:
    - molpx
  commands:
    - pytest -vv --pyargs molpx --cov=molpx --cov-report=xml --current-env --nbval-lax --duration=10
    - cp coverage.xml /tmp #  [linux]

about:
  home: https://github.com/gph82/projection_explorer
  license: GNU Lesser Public License v3+
  summary: "molPX: Molecular Projection Explorer"
